#!/bin/bash          

dir_source=source
dir_templates=templates
dir_static=static

template_header=`cat $dir_templates/header.html`
template_footer=`cat $dir_templates/footer.html`
template_nav=`cat $dir_templates/nav.html`



i=0
ls $dir_source/ | grep html | while read file
do
    array[$i]="$file"
    #echo $line
    cp $dir_source/$file $dir_static/$file

    sed -i -e "s/~header~/$template_header/g" $dir_static/$file
    sed -i -e "s/~footer~/$template_footer/g" $dir_static/$file
    sed -i -e "s/~nav~/$template_nav/g" $dir_static/$file
    rm -fr $dir_static/$file-e

    ((i++))
done
