#!/bin/bash          

dir_source=source
dir_templates=templates
dir_static=static

# Read list of blog posts currently available
i=0
ls $dir_source/ | grep html | while read file
do
    array[$i]="$file"
    #echo $line
    cp $dir_source/$file $dir_static/$file
    # POST PROCESS FILES HERE ADDING HTML ELEMENTS

    sed -i -e 's/~header~/<html>/g' $dir_static/$file
    sed -i -e 's/~footer~/<\/html>/g' $dir_static/$file
    sed -i -e 's/~nav~/<nav><\/nav>/g' $dir_static/$file
    rm -fr $dir_static/$file-e

    ((i++))
done
